-- seed_pipelines_darwin_dev.sql
--
-- GENERATED by DarwinSQL/scripts/seed_pipelines_darwin_dev.py — do not hand-edit.
-- Regenerate after any change to the req #3083 PLAN-JSON.
--
-- Req #3111 / deliverable 3 of req #3080: the 2026-07-25 Substrate Rebuild plan,
-- the acceptance fixture for the Swarm Orchestration feature, expressed in the
-- tables migration 076 creates.
--
-- *** darwin_dev ONLY. *** Production `darwin` stays EMPTY until the Primary's
-- live-plan cutover, which is a separate doctrine-governed act. Do not apply
-- this file to `darwin`.
--
-- Source plan: requirement #3083, 34 rows, 54 distinct requirements,
--              4 epics, 20 features.
--
-- ## Id allocation (explicit, so this file is idempotent and self-scoping)
--
--   epics                9001..9004
--   features             9001..9020
--   pipelines            9001
--   pipeline_steps       9000 + the plan step id (see below)
--   projects/categories  9001 / 9001 — owned by the fixture, created idempotently
--
-- ## plan step id -> pipeline_steps.id
--
-- OFFSET BY 9000. The plan's `step` values are already stable integers assigned
-- once and never renumbered (req #3080 design rule 4 / the 2026-07-25
-- normalization), which is exactly the contract pipeline_steps.id carries — but
-- they start at 1. Loading them verbatim would park AUTO_INCREMENT just above the
-- plan's highest step, so the next step created organically through the app would
-- take an id the plan claims as soon as it grows, and the next re-seed would die
-- 1062 mid-file with the teardown already applied. The offset keeps the mapping
-- readable (plan step 12 -> 9012) and collision-free. In the product these ids come
-- from AUTO_INCREMENT; only this fixture pins them.
--
--   1->9001, 2->9002, 3->9003, 4->9004, 5->9005, 6->9006, 7->9007, 8->9008, 9->9009, 23->9023, 33->9033, 34->9034, 21->9021, 10->9010, 26->9026, 28->9028, 25->9025, 11->9011, 22->9022, 12->9012, 13->9013, 14->9014, 16->9016, 17->9017, 31->9031, 18->9018, 19->9019, 20->9020, 38->9038, 39->9039, 40->9040, 41->9041, 42->9042, 43->9043
--
-- ## Mutation end-states this fixture carries (acceptance criteria)
--
--   * req-less step        step 7 — no requirement links; completed_at is the
--                          manual stamp, the one case the column exists for.
--   * dual-condition gate  step 3 — two dep rows of different kinds (step 1 +
--                          a wall-clock row). RECONSTRUCTED from req #3080 stage 0
--                          (s0.4); the live PLAN-JSON has no T: tokens because the
--                          normalization dropped them. The ONLY dep row here not
--                          present in the live plan.
--   * multi-req steps      steps 1, 12, 13, 19, 33 — launch units of 5, 7, 5, 3 and
--                          2 requirements (design rule 2).
--   * cross-epic step      step 19 — #3105 sits under a different epic than the
--                          step's dominant label, which is why labels attach at
--                          the requirement (design rule 10).
--   * dropped-without-     requirements the user pulled from the plan (#3065/#3074
--     residue              era) simply are not here — no tombstones, no residue.
--
-- Requirement rows are upserted with their LIVE metadata (title, status, model,
-- effort) because step state is DERIVED from requirement status (design rule 1):
-- without real statuses the fixture would render every step Scheduled and prove
-- nothing. machine_fk is remapped production->darwin_dev (2->74, 3->75); unmappable values
-- become NULL ("Any").
--
-- ## KNOWN DIVERGENCE — derived state vs the plan's stored `state` (STEP 19)
--
-- Deriving state from this fixture reproduces the plan's own `state` field for 33
-- of 34 rows. Step 19 is the exception: the plan says done, the derivation says
-- Running, because the step links #3083 — the TRACKING requirement — and a
-- tracking requirement stays in `development` for the entire life of the plan it
-- describes. The fixture is NOT adjusted to match. It stores no state at all, by
-- design, and hand-correcting the inputs to make a rule come out right is exactly
-- the move design rule 1 forbids.
--
-- The divergence is a REAL INPUT for the derivation engine (req #3112) and the
-- Primary doctrine (req #3116): a plan's own tracking requirement is a container,
-- not work, and a step that links one will pin itself Running forever unless the
-- rule excludes it. Recorded here rather than smoothed away so the engine work
-- has the case in hand.

-- The plan text carries em-dashes, ellipses and other non-ASCII; declare the
-- connection charset so a loader that does not default to utf8mb4 cannot mangle
-- or reject it. Load with DarwinSQL/scripts/load_sql.py (quote-aware splitter —
-- titles here contain both semicolons and # characters inside string literals).
SET NAMES utf8mb4;
USE darwin_dev;

-- ---------------------------------------------------------------------------
-- Teardown — FK-safe order, scoped to this fixture's ids.
--
-- pipeline_step_deps goes FIRST and explicitly: dep_step_fk is ON DELETE
-- RESTRICT, so deleting the pipeline while step-to-step edges exist is refused
-- (this plan has 30 of them). That two-phase teardown is the documented contract
-- from migration 076 — not a quirk of this file.
-- ---------------------------------------------------------------------------
DELETE FROM pipeline_step_deps WHERE step_fk IN (SELECT id FROM pipeline_steps WHERE pipeline_fk = 9001);
DELETE FROM pipeline_step_requirements WHERE step_fk IN (SELECT id FROM pipeline_steps WHERE pipeline_fk = 9001);
DELETE FROM pipeline_steps WHERE pipeline_fk = 9001;
DELETE FROM pipelines WHERE id = 9001;
-- Detach requirements before features go, so fk_requirements_feature (SET NULL)
-- never has to fire mid-load and leave a half-linked state.
--
-- Scoped to the EXACT ids this file is about to insert, never a BETWEEN range.
-- Explicit ids at 9001+ leave AUTO_INCREMENT immediately above the fixture band, so
-- the next organically-created row lands exactly where a growing range would
-- expand — and a later plan with one more feature label would delete it.
UPDATE requirements SET feature_fk = NULL WHERE feature_fk IN (9001, 9002, 9003, 9004, 9005, 9006, 9007, 9008, 9009, 9010, 9011, 9012, 9013, 9014, 9015, 9016, 9017, 9018, 9019, 9020);
DELETE FROM features WHERE id IN (9001, 9002, 9003, 9004, 9005, 9006, 9007, 9008, 9009, 9010, 9011, 9012, 9013, 9014, 9015, 9016, 9017, 9018, 9019, 9020);
DELETE FROM epics WHERE id IN (9001, 9002, 9003, 9004);

-- ---------------------------------------------------------------------------
-- The fixture's OWN project + category.
--
-- The plan's requirements carry PRODUCTION category ids, and
-- requirements.category_fk is NOT NULL -> categories ON DELETE RESTRICT — the
-- same cross-database hazard the machine_fk remap exists for. Reusing them works
-- on today's darwin_dev only because the ids happen to coincide; against a
-- darwin_dev rebuilt from recreate_darwin_dev.sql the load would fail 1452 AFTER
-- the teardown above had dropped the previous fixture. Owning these two rows
-- removes the assumption.
--
-- Created idempotently and deliberately NOT torn down: the upserted requirements
-- keep pointing at the category, and the FK is RESTRICT.
-- ---------------------------------------------------------------------------
INSERT INTO projects (id, project_name, creator_fk) VALUES
  (9001, 'Swarm Orchestration Fixture', '37df7531-000d-4470-8be4-1792d8261f69')
AS new ON DUPLICATE KEY UPDATE project_name = new.project_name;

INSERT INTO categories (id, category_name, project_fk, creator_fk) VALUES
  (9001, 'Swarm Orchestration Fixture', 9001, '37df7531-000d-4470-8be4-1792d8261f69')
AS new ON DUPLICATE KEY UPDATE category_name = new.category_name;

-- ---------------------------------------------------------------------------
-- Epics (4) — the top of Epic > Feature > Story.
-- ---------------------------------------------------------------------------
INSERT INTO epics (id, title, description, category_fk, creator_fk, sort_order) VALUES
  (9001, 'Swarm Substrate Rebuild', 'Epic from the 2026-07-25 Substrate Rebuild plan (req #3083).', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 0),
  (9002, 'Application Backlog', 'Epic from the 2026-07-25 Substrate Rebuild plan (req #3083).', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 1),
  (9003, 'Swarm Orchestration Feature', 'Epic from the 2026-07-25 Substrate Rebuild plan (req #3083).', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 2),
  (9004, 'Primary and Swarm Agentic Integration', 'Epic from the 2026-07-25 Substrate Rebuild plan (req #3083).', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 3);

-- ---------------------------------------------------------------------------
-- Features (20) — one per distinct feature label, linked to its epic.
-- ---------------------------------------------------------------------------
INSERT INTO features (id, title, description, feature_status, epic_fk, category_fk, creator_fk, sort_order) VALUES
  (9001, 'Session Drain', 'Feature under epic "Swarm Substrate Rebuild", from the Substrate Rebuild plan (req #3083).', 'active', 9001, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 0),
  (9002, 'MCP Hardening', 'Feature under epic "Swarm Substrate Rebuild", from the Substrate Rebuild plan (req #3083).', 'active', 9001, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 1),
  (9003, 'Substrate Safety', 'Feature under epic "Swarm Substrate Rebuild", from the Substrate Rebuild plan (req #3083).', 'active', 9001, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 2),
  (9004, 'Green Baseline', 'Feature under epic "Swarm Substrate Rebuild", from the Substrate Rebuild plan (req #3083).', 'active', 9001, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 3),
  (9005, 'WSL Parity', 'Feature under epic "Swarm Substrate Rebuild", from the Substrate Rebuild plan (req #3083).', 'active', 9001, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 4),
  (9006, 'WSL Backlog', 'Feature under epic "Application Backlog", from the Substrate Rebuild plan (req #3083).', 'active', 9002, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 5),
  (9007, 'Agentic Telemetry', 'Feature under epic "Application Backlog", from the Substrate Rebuild plan (req #3083).', 'active', 9002, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 6),
  (9008, 'Clone Substrate', 'Feature under epic "Swarm Substrate Rebuild", from the Substrate Rebuild plan (req #3083).', 'active', 9001, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 7),
  (9009, 'Backlog Wave', 'Feature under epic "Application Backlog", from the Substrate Rebuild plan (req #3083).', 'active', 9002, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 8),
  (9010, 'Post-Wave Batch', 'Feature under epic "Application Backlog", from the Substrate Rebuild plan (req #3083).', 'active', 9002, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 9),
  (9011, 'Primary Parity', 'Feature under epic "Swarm Substrate Rebuild", from the Substrate Rebuild plan (req #3083).', 'active', 9001, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 10),
  (9012, 'Swarm Orchestration Feature', 'Feature under epic "Swarm Orchestration Feature", from the Substrate Rebuild plan (req #3083).', 'active', 9003, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 11),
  (9013, 'Agent Infra Leverage', 'Feature under epic "Primary and Swarm Agentic Integration", from the Substrate Rebuild plan (req #3083).', 'active', 9004, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 12),
  (9014, 'Foundation Wave', 'Feature under epic "Swarm Orchestration Feature", from the Substrate Rebuild plan (req #3083).', 'active', 9003, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 13),
  (9015, 'API & Table Wave', 'Feature under epic "Swarm Orchestration Feature", from the Substrate Rebuild plan (req #3083).', 'active', 9003, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 14),
  (9016, 'Visualizer & Doctrine Wave', 'Feature under epic "Swarm Orchestration Feature", from the Substrate Rebuild plan (req #3083).', 'active', 9003, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 15),
  (9017, 'Acceptance', 'Feature under epic "Swarm Orchestration Feature", from the Substrate Rebuild plan (req #3083).', 'active', 9003, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 16),
  (9018, 'Polish & Showcase', 'Feature under epic "Swarm Orchestration Feature", from the Substrate Rebuild plan (req #3083).', 'active', 9003, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 17),
  (9019, 'Design Discussion', 'Feature under epic "Swarm Orchestration Feature", from the Substrate Rebuild plan (req #3083).', 'active', 9003, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 18),
  (9020, 'Swarm Doctrine', 'Carries the cross-epic requirement in plan step 19 — the launch unit spans epics, which is why labels attach at the requirement (req #3080 design rule 10).', 'active', 9001, 9001, '37df7531-000d-4470-8be4-1792d8261f69', 19);

-- ---------------------------------------------------------------------------
-- Requirements (54) — upserted with live metadata, then filed under their
-- feature. pipeline_step_requirements.requirement_fk is ON DELETE RESTRICT, so
-- every referenced requirement must exist before the junction rows load.
--
-- ON DUPLICATE KEY UPDATE, not plain INSERT: darwin_dev already holds some of
-- these ids, and the fixture must refresh their status (step state is derived
-- from it) without disturbing anything else about the row.
-- ---------------------------------------------------------------------------
INSERT INTO requirements (id, title, requirement_status, coordination_type, ai_model, effort, category_fk, creator_fk, machine_fk, feature_fk, started_at, completed_at) VALUES
  (3041, 'Make the DarwinAI-Config base clone handled commonly with all sub-repos: hygiene preconditions must be ff-only SYNC, never SAVE. No operation may commit/push the live base clone except the primary''s own /save-primary-claude.', 'wontfix', 'implemented', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 9003, NULL, '2026-07-25T11:03:58'),
  (3045, 'Collect agent telemetry ', 'met', 'deployed', 'sonnet', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9009, NULL, '2026-07-26T08:55:39'),
  (3050, 'darwin-mcp rearchitecture: Lambda-Rest as single DB gateway (clean-sheet REST transport)', 'met', 'implemented', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 9001, NULL, '2026-07-25T17:34:59'),
  (3051, 'Documents page becomes editable', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9009, NULL, '2026-07-26T10:41:50'),
  (3056, 'Views show autonomy', 'met', 'implemented', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 75, 9001, NULL, '2026-07-25T10:05:13'),
  (3057, 'Junction POST returns 500 after committing the row (breaks Features linking)', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9009, NULL, '2026-07-26T09:15:30'),
  (3058, 'memory/api-gateway.md route tables are stale — full reconciliation', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9008, NULL, '2026-07-26T08:24:48'),
  (3059, 'Map pymysql IntegrityError to HTTP 409 in Lambda-Rest', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9009, NULL, '2026-07-26T10:04:37'),
  (3060, 'E2E coverage for the editable agent instruction registry', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9010, NULL, '2026-07-26T11:46:23'),
  (3061, 'Two stale backend test files fail on schema drift', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9004, NULL, '2026-07-26T00:59:00'),
  (3063, 'Instruction Edit In Place', 'met', 'implemented', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 9001, NULL, '2026-07-25T11:26:25'),
  (3064, 'Aggregator Card Polish', 'met', 'implemented', 'sonnet', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 75, 9001, NULL, '2026-07-25T09:54:20'),
  (3065, 'Agent Context Polish', 'met', 'implemented', 'sonnet', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 75, 9006, NULL, '2026-07-26T11:03:04'),
  (3067, 'Instructions Table View — hardened generic edit-in-place table pattern', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9009, NULL, '2026-07-26T23:30:27'),
  (3068, 'Instructions need proper English titles, not kebab-case slugs', 'met', 'planned', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 9001, NULL, '2026-07-25T11:26:26'),
  (3069, 'Statusline DevServ indicator never shows on dash-based /bin/sh (WSL/Linux) — works on macOS only', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9003, NULL, '2026-07-25T22:45:09'),
  (3071, 'Replace remaining window.confirm calls under /agents with the house dialog pattern', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9009, NULL, '2026-07-26T09:13:37'),
  (3072, 'Swarm substrate Phase 0+1 — eliminate shared-clone git corruption class (de-symlink, Primary-only sync, remove worker-to-Primary writes, full git audit)', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9003, NULL, '2026-07-25T20:49:24'),
  (3074, 'Darwin Primary AI / Swarm Worker leverage Agent infra', 'approved', 'discuss', 'fable', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9013, NULL, NULL),
  (3075, 'agent_instructions.sort_order has no per-agent uniqueness guard — decide the invariant', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9009, NULL, '2026-07-26T09:49:34'),
  (3076, 'Test InstructionDeleteDialog data-loss vs boot-impact wording', 'met', 'deployed', 'opus', 'low', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9009, NULL, '2026-07-26T08:53:14'),
  (3077, 'Swarm substrate Phases 2-4 — per-session clone provisioning from local mirrors; retire git-worktree machinery (full worker independence)', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9008, NULL, '2026-07-26T02:53:18'),
  (3078, 'darwin-mcp: bounded list reads — Lambda 6 MB response ceiling 502s large resources', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9002, NULL, '2026-07-25T19:03:14'),
  (3079, 'WSL: migrate mcp_credentials.sh to the #3050 Cognito variable set (new darwin-mcp daemon fails with ''DB_HOST'' error until done)', 'met', 'discuss', 'sonnet', 'medium', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 75, 9005, NULL, '2026-07-26T02:14:10'),
  (3080, 'Swarm Orchestration Feature: discuss session to spec and file the requirements for a durable pipeline data type (plans stored in Darwin, rendered in SwarmView, executed by Primary AI)', 'met', 'discuss', 'fable', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9012, NULL, '2026-07-27T01:25:19'),
  (3082, 'Primary AI substrate parity - relocate Primary to ~/darwin/primary via the unified clone pattern (pipeline Stage 5)', 'swarm_ready', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9011, NULL, NULL),
  (3083, 'Substrate Rebuild Pipeline - plan tracking (single source of truth for the plan page)', 'development', 'implemented', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9012, '2026-07-25T23:32:44', NULL),
  (3084, 'WSL verification 1 of 3: full MCP validation', 'met', 'implemented', 'sonnet', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 75, 9005, NULL, '2026-07-26T03:19:32'),
  (3085, 'WSL verification 2 of 3: full swarm session independence', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 75, 9005, NULL, '2026-07-26T09:42:38'),
  (3086, 'WSL verification 3 of 3: full primary session independence', 'swarm_ready', 'discuss', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 75, 9005, NULL, NULL),
  (3087, 'Primary gate execution + B5a cutover for clone substrate (#3077 Stage 3/4)', 'met', 'implemented', 'fable', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9008, NULL, '2026-07-26T06:01:35'),
  (3088, 'Substrate remediation: R18 freshness contract, R19 no-hardlinks, B3 skill cutover, R6 attribution coverage + gap tests', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9008, NULL, '2026-07-26T05:25:08'),
  (3089, 'provision-repo.sh venv step uses system python3 (3.9) — fastmcp needs 3.10+; canary-1 venv=failed', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9010, NULL, '2026-07-26T11:28:16'),
  (3090, 'Clone substrate canary-2: multi-repo session lifecycle validation (throwaway)', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9008, NULL, '2026-07-26T08:14:15'),
  (3091, 'Clone sessions hit the Claude Code folder-trust dialog — pre-trust session dirs at launch (blocks all autonomous workers)', 'met', 'implemented', 'fable', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9008, NULL, '2026-07-26T08:00:25'),
  (3092, 'Persist per-repo provisioning telemetry (mirror_action, venv) into the swarm session record', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9010, NULL, '2026-07-26T11:48:11'),
  (3093, '/swarm-complete Step 5.6 worker guard never fires — mcp-restart-if-stale.sh reads $PWD, but Step 0(d) cd s to mainRepoPath', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9010, NULL, '2026-07-26T11:29:45'),
  (3094, 'POST /profiles read-back returns other users rows (WHERE id=0 on a non-auto-increment id)', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9010, NULL, '2026-07-26T11:33:28'),
  (3095, 'Ground-truth breakdown of the Claude Code base token figure', 'development', 'planned', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 75, 9007, '2026-07-26T11:06:03', NULL),
  (3096, 'Per-document actual-token capture for architecture/autoload docs', 'met', 'deployed', 'sonnet', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 9007, NULL, '2026-07-26T12:43:30'),
  (3097, 'Post-relocation Primary verification battery (Mac mini) — executed by the NEW primary session', 'swarm_ready', 'implemented', 'fable', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9011, NULL, NULL),
  (3098, 'Capture machine, model, and effort for agent telemetry runs', 'met', 'deployed', 'sonnet', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 9007, NULL, '2026-07-26T22:06:34'),
  (3105, 'Swarm-Complete can RDS Snapshot', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9020, NULL, '2026-07-27T00:33:55'),
  (3108, 'Cooperative inter-Claude message system: proactive status communication between Primary(s) and workers — design discussion', 'approved', 'discuss', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 9019, NULL, NULL),
  (3110, 'Swarm Orchestration: groom the full design intent into Swarm Architect documentation', 'met', 'deployed', 'fable', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9014, NULL, '2026-07-27T01:52:32'),
  (3111, 'Swarm Orchestration: schema foundation - epic hierarchy + pipelines data type (migration, routes, darwin_dev fixtures)', 'development', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9014, '2026-07-27T01:31:13', NULL),
  (3112, 'Swarm Orchestration: ordering & derivation engine - pure JS module with self-checking invariants (vitest)', 'met', 'deployed', 'fable', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9014, NULL, '2026-07-27T02:14:14'),
  (3113, 'Swarm Orchestration: MCP pipelines API - bounded resources + echo-verified mutation tools', 'swarm_ready', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9015, NULL, NULL),
  (3114, 'Swarm Orchestration: SwarmView pipelines UI - hooks, routes, list page + plan-rows table view', 'swarm_ready', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9015, NULL, NULL),
  (3115, 'Swarm Orchestration: Plan visualizer (no time anchor) - epic bands, swim lanes, batch boxes, drag-pan + three-level zoom', 'swarm_ready', 'deployed', 'fable', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9016, NULL, NULL),
  (3116, 'Swarm Orchestration: Primary execution doctrine + fail-loud pipeline watchdog', 'swarm_ready', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9016, NULL, NULL),
  (3117, 'Swarm Orchestration: cost rollup - server-side precompute at session completion + Time/Tokens display', 'swarm_ready', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9016, NULL, NULL),
  (3118, 'Swarm Orchestration: E2E + mutation-case acceptance battery', 'swarm_ready', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9017, NULL, NULL),
  (3119, 'Swarm Orchestration: final polish & showcase - full live 3083 plan in darwin_dev, dev-server walkthrough, executive summary', 'swarm_ready', 'implemented', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 74, 9018, NULL, NULL)
AS new ON DUPLICATE KEY UPDATE
  title = new.title,
  requirement_status = new.requirement_status,
  coordination_type = new.coordination_type,
  ai_model = new.ai_model,
  effort = new.effort,
  machine_fk = new.machine_fk,
  feature_fk = new.feature_fk,
  started_at = new.started_at,
  completed_at = new.completed_at;

-- ---------------------------------------------------------------------------
-- The pipeline. `active` is a STORED, human/Primary-controlled declaration of
-- intent about the plan as a whole — the only hand-set lifecycle in the feature.
-- ---------------------------------------------------------------------------
INSERT INTO pipelines (id, title, description, pipeline_status, machine_fk, creator_fk, started_at) VALUES
  (9001, 'Substrate Rebuild Pipeline', 'Recover from the .git/index corruption incident, eliminate the shared-clone corruption class, rebuild provisioning on per-session clones, then run the max-parallel feature DAG. Source of truth: requirement #3083.', 'active', 74, '37df7531-000d-4470-8be4-1792d8261f69', '2026-07-24 00:00:00');

-- ---------------------------------------------------------------------------
-- Steps (34) — one per plan row, id = plan step id.
--
-- NO state column is written because none exists: a step's state is derived from
-- its linked requirements (design rule 1). The plan's own `state` field
-- (done/active/pending) is therefore NOT stored — it is reproducible from the
-- requirement statuses upserted above, and storing it is exactly the hand-edited
-- field that let plan row 13 read "Scheduled" while five sessions ran.
--
-- title is the plan summary cut to VARCHAR(256) at a word boundary; `notes` holds
-- the full untruncated text, including the evidence and disposition prose.
-- ---------------------------------------------------------------------------
INSERT INTO pipeline_steps (id, pipeline_fk, title, run, notes, completed_at, creator_fk) VALUES
  (9001, 9001, 'Drain: close every open swarm session so substrate surgery starts with zero in-flight work', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9002, 9001, 'Bound every MCP list read under Lambda''s 6 MB response ceiling; heavy columns move to by-id reads', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9003, 9001, 'Eliminate dual-path git access (symlinks deleted, all repos moved off Desktop into real dirs), audit every git call, pr-finalize made read-only, ff-only Primary sync, hard clean-Primary gate', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9004, 9001, 'Dispositioned wontfix; live scope folded into 3072 (W7 clean gate) and 3077 (C1 grep gate, C2 origin fingerprint)', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9005, 9001, 'Validation: first full worker lifecycle run clean on the repaired substrate (also fixed the statusline dev-server indicator)', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9006, 9001, 'Repair every pre-existing test failure - backend fixture drift, MCP count asserts, two harness scripts - so the full suite reads truly green', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9007, 9001, 'Record the all-passing regression baseline across every suite; the fixed reference point for the clone-substrate regression gate - RECORDED 2026-07-26: harness 3736/3736, Lambda-Rest 134, Cognito 18, mcp unit 252 / integration 688 / production 62 - all…', 'auto', 'Record the all-passing regression baseline across every suite; the fixed reference point for the clone-substrate regression gate - RECORDED 2026-07-26: harness 3736/3736, Lambda-Rest 134, Cognito 18, mcp unit 252 / integration 688 / production 62 - all passing', '2026-07-26 01:30:00', '37df7531-000d-4470-8be4-1792d8261f69'),
  (9008, 9001, 'MCP setup on machine 3 - strictly serial: (1) /primary-ai-sync brings the WSL workspace current, (2) req 3079 migrates credentials and stands up the darwin-mcp daemon. No step/time deps: eligible whenever the user is at the WSL box', 'manual', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9009, 9001, 'Verification 1 of 3 - full MCP validation: health, wrapper read+mutation round-trips, bounded list reads, all three darwin-mcp test tiers, auto-restart. No pipeline gate - runnable immediately after W1', 'manual', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9023, 9001, 'Agent Context polish (session 2439, machine 3). CORRECTED 2026-07-26: #3079 completed at 02:14Z, session created 02:17Z - it has run on the NEW daemon + credentials from birth. No stale-stack risk; normal lifecycle applies', 'manual', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9033, 9001, 'AGENTIC TELEMETRY BATCH - one swarm-start, two sessions: per-document actual-token capture for architecture documents (3096), machine/model/effort columns on agent telemetry runs (3098)', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9034, 9001, 'Ground-truth breakdown of the Claude Code base token figure (spawned by #3065). Discuss coordination on the Windows/WSL machine — user starts and drives it there.', 'manual', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9021, 9001, 'MILESTONE 1 (R20): mirror layer + protections land first - mirror-update.sh with the R18 single-flight freshness contract (mandatory synchronous fetch at every provision, per-repo lock, loud failure) and provision-repo.sh with R19 --no-hardlinks…', 'auto', 'MILESTONE 1 (R20): mirror layer + protections land first - mirror-update.sh with the R18 single-flight freshness contract (mandatory synchronous fetch at every provision, per-repo lock, loud failure) and provision-repo.sh with R19 --no-hardlinks fully-private clones (greenfield-verified). Reviewable unit before any cutover work', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9010, 9001, 'Clone substrate core: B3 discovery + provisioning cutover (flag-gated), dual-mode cleanup, worker git_op guard, docs - wrapped in feature review, gap analysis, and full regression vs the step-7 baseline', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9026, 9001, 'Substrate remediation from gate findings: R19 --no-hardlinks (tests assert the opposite today), R18 FRESH_WINDOW dedup + stale_ok degrade, B3 skill cutover (/swarm-start + /swarm-resume still hardcode wt- paths — breaks at flip time), R6 attribution…', 'auto', 'Substrate remediation from gate findings: R19 --no-hardlinks (tests assert the opposite today), R18 FRESH_WINDOW dedup + stale_ok degrade, B3 skill cutover (/swarm-start + /swarm-resume still hardcode wt- paths — breaks at flip time), R6 attribution coverage fix, MED/LOW gap tests. Blocks the flip and canaries.', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9028, 9001, 'CANARY CATCH (major): clone sessions are new project roots — Claude Code folder-trust dialog blocked both canaries; worktrees had inherited trust via their .git pointer. Fixed same-day: trust-session.sh pre-registers the trust entry in ~/.claude.json,…', 'auto', 'CANARY CATCH (major): clone sessions are new project roots — Claude Code folder-trust dialog blocked both canaries; worktrees had inherited trust via their .git pointer. Fixed same-day: trust-session.sh pre-registers the trust entry in ~/.claude.json, wired into worker-launch-batch.sh before backend dispatch. Landed fa7ed2b.', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9025, 9001, 'Primary gate execution: G-feature + G-gap reviews (done — 5 deviations, 12 gaps found), independent G-regression after remediation, then B5a flag flip (LAYOUT_DEFAULT_PROVISIONING -> clone) deployed via /primary-ai-swarm-complete. Mirrors+sessions layout…', 'auto', 'Primary gate execution: G-feature + G-gap reviews (done — 5 deviations, 12 gaps found), independent G-regression after remediation, then B5a flag flip (LAYOUT_DEFAULT_PROVISIONING -> clone) deployed via /primary-ai-swarm-complete. Mirrors+sessions layout created and 7 mirrors seeded 2026-07-26.', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9011, 9001, 'Canary: a docs-only requirement runs the first clone-provisioned session through its entire lifecycle', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9022, 9001, 'Clone canary 2 (Mac mini, #3077 R13): throwaway requirement exercising what canary 1 cannot - >=2 repos, mid-session /hygiene checkout of a third, npm install in the session clone, dev-server registration, pause -> resume -> undo round-trip, deploy path,…', 'auto', 'Clone canary 2 (Mac mini, #3077 R13): throwaway requirement exercising what canary 1 cannot - >=2 repos, mid-session /hygiene checkout of a third, npm install in the session clone, dev-server registration, pause -> resume -> undo round-trip, deploy path, and the mid-flight rm -rf isolation test. Throwaway req filed at execution time', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9012, 9001, 'Seven parallel sessions on the proven substrate: house dialog pattern under /agents, IntegrityError-to-409 mapping, junction-POST 500 fix, editable Documents page, agent telemetry collection, delete-dialog wording test, sort-order invariant decision', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9013, 9001, 'POST-WAVE BATCH - one swarm-start, five sessions: provision-repo.sh venv python3.10+ fix (3089), per-repo provisioning telemetry persisted to the session record (3092), mcp-restart-if-stale.sh cross-session write to the PRIMARY clone (3093), E2E coverage…', 'auto', 'POST-WAVE BATCH - one swarm-start, five sessions: provision-repo.sh venv python3.10+ fix (3089), per-repo provisioning telemetry persisted to the session record (3092), mcp-restart-if-stale.sh cross-session write to the PRIMARY clone (3093), E2E coverage for the editable agent instruction registry (3060), SECURITY POST /profiles read-back cross-tenant leak (3094)', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9014, 9001, 'Instructions Table View - hardened generic edit-in-place table pattern', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9016, 9001, 'Verification 2 of 3 - WSL CLONE TESTING (mirror of the mini canaries on machine 3): mirrors + session-clone layout via the same scripts, real /swarm-start full lifecycle, write isolation, machine-pin routing. The clone mechanism is proven per-machine,…', 'manual', 'Verification 2 of 3 - WSL CLONE TESTING (mirror of the mini canaries on machine 3): mirrors + session-clone layout via the same scripts, real /swarm-start full lifecycle, write isolation, machine-pin routing. The clone mechanism is proven per-machine, never assumed portable', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9017, 9001, 'PLAN-COMPLETION GATE. Relocate Primary to ~/darwin/primary via the same clone pattern as workers; migrate memory, config, and MCP daemon; decommission the old path (no dual-path overlap); validation battery ends with a canary swarm launch from the new home', 'manual', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9031, 9001, 'Human-verified #3082 battery, executed BY the new primary session at ~/darwin/primary after cutover: layout resolution, MCP, statusline walk-ups, dev server, a canary /swarm-start from the new home, hooks/darcfg, old-path decommission audit. Failures…', 'manual', 'Human-verified #3082 battery, executed BY the new primary session at ~/darwin/primary after cutover: layout resolution, MCP, statusline walk-ups, dev server, a canary /swarm-start from the new home, hooks/darcfg, old-path decommission audit. Failures file defects, never inline patches.', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9018, 9001, 'Verification 3 of 3 - full primary session independence: execute the step-12 runbook on machine 3, old-path decommission, validation battery from the new home. Completes WSL parity', 'manual', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9019, 9001, 'Cherry: discuss session specs the pipelines-as-data feature and files its follow-on requirements - this plan is its seed dataset, held by tracking req 3083 (single source of truth this page renders from) + BATCHED same launch: swarm-complete…', 'auto', 'Cherry: discuss session specs the pipelines-as-data feature and files its follow-on requirements - this plan is its seed dataset, held by tracking req 3083 (single source of truth this page renders from) + BATCHED same launch: swarm-complete RDS-snapshots without asking permission (3105, cross-epic per rule 10)', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9020, 9001, 'Darwin Primary AI and swarm workers leverage the Agent infrastructure (final step of the plan)', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9038, 9001, 'FOUNDATION BATCH - one swarm-start, three sessions: design-intent grooming into Swarm Architect docs (3110), schema foundation - epics/features/requirements hierarchy + pipelines/pipeline_steps/step-requirements/step-deps tables + API routes + darwin_dev…', 'auto', 'FOUNDATION BATCH - one swarm-start, three sessions: design-intent grooming into Swarm Architect docs (3110), schema foundation - epics/features/requirements hierarchy + pipelines/pipeline_steps/step-requirements/step-deps tables + API routes + darwin_dev fixtures from this plan (3111), pure-JS ordering/derivation engine with self-checking invariants (3112)', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9039, 9001, 'API & TABLE BATCH: MCP pipelines resources + echo-verified mutation tools with single-read render (3113); SwarmView pipelines hooks/routes/list page + plan-rows table view per pipeline-plan-tracking rules (3114)', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9040, 9001, 'VISUALIZER & DOCTRINE BATCH: Plan (no time anchor) visualizer with drag-pan + three-level zoom, clickable steps/reqs/epics (3115); Primary execution doctrine + 8-case mutation playbook + fail-loud watchdog (3116); server-side cost rollup + Time/Tokens…', 'auto', 'VISUALIZER & DOCTRINE BATCH: Plan (no time anchor) visualizer with drag-pan + three-level zoom, clickable steps/reqs/epics (3115); Primary execution doctrine + 8-case mutation playbook + fail-loud watchdog (3116); server-side cost rollup + Time/Tokens enable (3117)', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9041, 9001, 'Acceptance battery: Playwright E2E over the seeded darwin_dev plan + replay of all 8 recorded mutation classes via MCP tools, asserting derived state and invariant-clean rendered order after each', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9042, 9001, 'FINAL POLISH & SHOWCASE (implemented - the epic''s only user-review stop): re-seed darwin_dev with the full live 3083 plan, cosmetic polish pass, dev server deep-linked to /swarm/pipelines, concise executive summary; user checks all features', 'auto', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9043, 9001, 'Design discussion (discuss, user-driven): cooperative inter-Claude message system - grounded by the shipped orchestration core + Primary doctrine; informs future proactive Primary/worker communication', 'manual', NULL, NULL, '37df7531-000d-4470-8be4-1792d8261f69');

-- ---------------------------------------------------------------------------
-- Step -> requirement links (55). A step is a LAUNCH UNIT: steps 1, 33, 12, 13, 19, 38, 39, 40 carry
-- more than one requirement because those requirements went out in ONE
-- swarm-start (design rule 2).
-- ---------------------------------------------------------------------------
INSERT INTO pipeline_step_requirements (step_fk, requirement_fk) VALUES
  (9001, 3050),
  (9001, 3056),
  (9001, 3063),
  (9001, 3064),
  (9001, 3068),
  (9002, 3078),
  (9003, 3072),
  (9004, 3041),
  (9005, 3069),
  (9006, 3061),
  (9008, 3079),
  (9009, 3084),
  (9023, 3065),
  (9033, 3096),
  (9033, 3098),
  (9034, 3095),
  (9021, 3077),
  (9010, 3077),
  (9026, 3088),
  (9028, 3091),
  (9025, 3087),
  (9011, 3058),
  (9022, 3090),
  (9012, 3071),
  (9012, 3059),
  (9012, 3057),
  (9012, 3051),
  (9012, 3045),
  (9012, 3076),
  (9012, 3075),
  (9013, 3089),
  (9013, 3092),
  (9013, 3093),
  (9013, 3060),
  (9013, 3094),
  (9014, 3067),
  (9016, 3085),
  (9017, 3082),
  (9031, 3097),
  (9018, 3086),
  (9019, 3080),
  (9019, 3083),
  (9019, 3105),
  (9020, 3074),
  (9038, 3110),
  (9038, 3111),
  (9038, 3112),
  (9039, 3113),
  (9039, 3114),
  (9040, 3115),
  (9040, 3116),
  (9040, 3117),
  (9041, 3118),
  (9042, 3119),
  (9043, 3108);

-- ---------------------------------------------------------------------------
-- Dependency edges from the plan (39). Structured rows, never prose
-- (design rule 4). Exactly one of dep_step_fk / time_at per row. dep_step_fk is
-- ON DELETE RESTRICT, which is what makes a referenced step undeletable.
-- ---------------------------------------------------------------------------
INSERT INTO pipeline_step_deps (step_fk, dep_step_fk, time_at) VALUES
  (9003, 9001, NULL),
  (9004, 9003, NULL),
  (9005, 9003, NULL),
  (9006, 9005, NULL),
  (9007, 9006, NULL),
  (9009, 9008, NULL),
  (9033, 9023, NULL),
  (9034, 9023, NULL),
  (9021, 9007, NULL),
  (9010, 9021, NULL),
  (9026, 9010, NULL),
  (9028, 9025, NULL),
  (9025, 9010, NULL),
  (9025, 9026, NULL),
  (9011, 9025, NULL),
  (9022, 9011, NULL),
  (9012, 9011, NULL),
  (9012, 9022, NULL),
  (9012, 9028, NULL),
  (9013, 9012, NULL),
  (9014, 9012, NULL),
  (9014, 9013, NULL),
  (9016, 9009, NULL),
  (9016, 9011, NULL),
  (9017, 9012, NULL),
  (9017, 9013, NULL),
  (9017, 9014, NULL),
  (9031, 9017, NULL),
  (9018, 9016, NULL),
  (9018, 9017, NULL),
  (9019, 9014, NULL),
  (9020, 9017, NULL),
  (9020, 9031, NULL),
  (9038, 9019, NULL),
  (9039, 9038, NULL),
  (9040, 9039, NULL),
  (9041, 9040, NULL),
  (9042, 9041, NULL),
  (9043, 9040, NULL);

-- ---------------------------------------------------------------------------
-- THE DUAL-CONDITION GATE (s0.4) — reconstructed, and separated from the block
-- above so its provenance cannot be mistaken.
--
-- req #3080, plan stage 0: "s0.4 gate: #3050 session completed AND 2h time gate
-- 06:31:38 PDT (done — note: DUAL-condition gate, two independent wait
-- mechanisms)". The live PLAN-JSON carries no T: tokens: the 2026-07-25
-- normalization that replaced the 0/2a/Wx/Px ids dropped the wall-clock condition
-- with the stage numbering. This row restores it on the step that actually waited
-- on it — step 3 (#3072, the first substrate surgery), which already gates on
-- step 1 (the drain, where #3050 landed). Step 3 therefore ends up with two dep
-- rows of DIFFERENT kinds, which is what a dual-condition gate is and what the
-- acceptance criterion asks this schema to prove it can hold.
-- ---------------------------------------------------------------------------
INSERT INTO pipeline_step_deps (step_fk, dep_step_fk, time_at) VALUES
  (9003, NULL, '2026-07-24 06:31:38');

-- Verification the loader can eyeball:
--   SELECT COUNT(*) FROM pipeline_steps             WHERE pipeline_fk = 9001;  -- 34
--   SELECT COUNT(*) FROM pipeline_step_requirements WHERE step_fk IN (SELECT id FROM pipeline_steps WHERE pipeline_fk = 9001);  -- 55
--   SELECT COUNT(*) FROM pipeline_step_deps         WHERE step_fk IN (SELECT id FROM pipeline_steps WHERE pipeline_fk = 9001);  -- 40
