-- seed_pipelines_darwin_dev.sql
--
-- GENERATED by DarwinSQL/scripts/seed_pipelines_darwin_dev.py — do not hand-edit.
-- Regenerate after any change to the req #3083 PLAN-JSON.
--
-- Req #3111 / deliverable 3 of req #3080: the 2026-07-25 Substrate Rebuild plan,
-- the acceptance fixture for the Swarm Orchestration feature, expressed in the
-- tables migration 076 creates.
--
-- *** darwin_dev ONLY. *** NEVER apply this file to production `darwin`.
-- It used to be safe to say `darwin` was simply empty. The Primary's live-plan
-- cutover has since landed and production carries the real plan, so these
-- 9001-band rows would sit alongside live ones rather than in an empty table
-- (req #3147).
--
-- Source plan: requirement #3083, 42 rows, 67 distinct requirements,
--              4 epics.
--
-- NO FEATURE LAYER (req #3355). Migration 20260811033413 dropped `features`,
-- `feature_test_cases` and `requirements.feature_fk`, so this fixture emits
-- neither the feature rows nor the requirement->feature link it used to. A
-- requirement reaches this plan through its STEP LINK and nothing else. Epics
-- are unaffected and still emitted.
--
-- ## Id allocation (explicit, so this file is idempotent and self-scoping)
--
--   epics                9001..9004
--   pipelines            9001
--   pipeline_steps       9000 + the plan step id (see below)
--   projects/categories  9001 / 9001 — owned by the fixture, created idempotently
--
-- ## plan step id -> pipeline_steps.id
--
-- OFFSET BY 9000. The plan's `step` values are already stable integers assigned
-- once and never renumbered (req #3080 design rule 4 / the 2026-07-25
-- normalization), which is exactly the contract pipeline_steps.id carries — but
-- they start at 1. Loading them verbatim would park AUTO_INCREMENT just above the
-- plan's highest step, so the next step created organically through the app would
-- take an id the plan claims as soon as it grows, and the next re-seed would die
-- 1062 mid-file with the teardown already applied. The offset keeps the mapping
-- readable (plan step 12 -> 9012) and collision-free. In the product these ids come
-- from AUTO_INCREMENT; only this fixture pins them.
--
--   1->9001, 2->9002, 3->9003, 4->9004, 5->9005, 6->9006, 7->9007, 8->9008, 9->9009, 23->9023, 33->9033, 34->9034, 21->9021, 10->9010, 26->9026, 28->9028, 25->9025, 11->9011, 22->9022, 12->9012, 13->9013, 14->9014, 16->9016, 17->9017, 31->9031, 18->9018, 19->9019, 20->9020, 38->9038, 39->9039, 40->9040, 41->9041, 42->9042, 43->9043, 44->9044, 45->9045, 46->9046, 47->9047, 48->9048, 49->9049, 50->9050, 51->9051
--
-- ## Mutation end-states this fixture carries (acceptance criteria)
--
--   * req-less step        step 7 — no requirement links; completed_at is the
--                          manual stamp, the one case the column exists for.
--   * dual-condition gate  step 3 — two dep rows of different kinds (step 1 +
--                          a wall-clock row). RECONSTRUCTED from req #3080 stage 0
--                          (s0.4); the live PLAN-JSON has no T: tokens because the
--                          normalization dropped them. The ONLY dep row here not
--                          present in the live plan.
--   * multi-req steps      launch units of >1 requirement, as step(count)
--                          pairs (design rule 2):
--                          1(5), 33(2), 12(7), 13(5), 19(3), 38(3), 39(2),
--                          40(4), 47(2), 49(3), 51(2).
--   * dropped-without-     requirements the user pulled from the plan (#3065/#3074
--     residue              era) simply are not here — no tombstones, no residue.
--
-- Requirement rows are upserted with their LIVE metadata (title, status, model,
-- effort) because step state is DERIVED from requirement status (design rule 1):
-- without real statuses the fixture would render every step Scheduled and prove
-- nothing. machine_fk carries no cross-database id: the plan's production
-- machine is emitted as a HOSTNAME lookup resolved against whichever `machines`
-- table this file is loaded into (#2=Macmini, #3=SJO-LT-C72929B), so a rebuilt darwin_dev
-- re-registering its machines under new ids cannot break the load. A hostname
-- the target does not know resolves to NULL ("Any").
--
-- ## DERIVED STATE vs the plan's stored `state`
--
-- Deriving state from this fixture reproduces the plan's own `state` field for 35
-- of 42 rows.
--
-- ### RESOLVED — the tracking-requirement divergence (req #3123)
--
-- This file used to carry a KNOWN DIVERGENCE note: step 19 derived Running
-- where the plan recorded done, because it links #3083 — this plan's own
-- TRACKING requirement, a container that stays in `development` for the
-- entire life of the plan it describes. Deriving pinned the step Running
-- forever. It was the sole divergence with a cause in the engine rather
-- than in the plan.
--
-- Req #3123 shipped the durable signal that closes it:
-- `requirements.tracking` (migration 20260731124830). A container is
-- subtracted from a step's GATING set before state is derived, so a step
-- whose links are all containers falls through to its own completed_at
-- exactly as a link-less step does, and a MIXED step lets its remaining
-- work decide. The flag is emitted below from the LIVE requirement read,
-- never hand-set here, and generation ABORTS if #3083 comes back unflagged.
--
-- Flagged as containers in this generation: #3083.
--
-- NOTE: every flagged container is now in a TERMINAL status, so the steps
-- linking one derive the same state with or without the exemption. This
-- file therefore CARRIES the signal but no longer DEMONSTRATES it. The
-- demonstration lives in the static JS fixture,
-- Darwin/src/SwarmView/pipelines/__tests__/substrateRebuildFixture.js, which
-- pins #3083 at `development` + tracking=1 on purpose (req #3169).
--
-- The exceptions, computed at generation time:
--
--   step 31  plan says pending  derivation says done
--   step 18  plan says pending  derivation says done
--   step 20  plan says pending  derivation says done
--   step 43  plan says pending  derivation says done
--   step 45  plan says active   derivation says done
--   step 47  plan says pending  derivation says done
--   step 51  plan says pending  derivation says done
--
-- The fixture is NOT adjusted to match. It stores no state at all, by design,
-- and hand-correcting the inputs to make a rule come out right is exactly the
-- move design rule 1 forbids. Causes found in THIS list:
--
--   * PLAN LAG — steps 31, 18, 20, 43, 45, 47, 51. Here the DERIVATION is the correct value: the stored
--     `state` field is hand-maintained and drifts the moment a session
--     starts or closes. That lag is the exact failure design rule 1 names
--     (plan row 13 read "Scheduled" while five sessions ran), so these rows
--     are the product FIXING the problem rather than describing it.
--     Read them as such only after ruling out a requirement missing from
--     the live read. A tracking container is no longer a candidate cause:
--     since req #3123 containers carry `requirements.tracking`, this
--     generator reads the flag live and exempts them before deriving.

-- The plan text carries em-dashes, ellipses and other non-ASCII; declare the
-- connection charset so a loader that does not default to utf8mb4 cannot mangle
-- or reject it. Load with DarwinSQL/scripts/load_sql.py (quote-aware splitter —
-- titles here contain both semicolons and # characters inside string literals).
SET NAMES utf8mb4;

-- darwin_dev ONLY. This used to be enforced by a `USE darwin_dev;` statement,
-- which enforced nothing: a `USE` re-points whoever executes it, so it protects
-- the file only for as long as nobody types the other database name. The line
-- below is a CONSTRAINT the caller is checked against before a connection is
-- opened, and a target list that omits `darwin` is an absolute production ban
-- (req #3196, DarwinSQL/scripts/db_guard.py).
-- darwin:targets = darwin_dev

-- ---------------------------------------------------------------------------
-- Teardown — FK-safe order, scoped to this fixture's ids.
--
-- pipeline_step_deps goes FIRST and explicitly: dep_step_fk is ON DELETE
-- RESTRICT, so deleting the pipeline while step-to-step edges exist is refused
-- (this plan has 45 of them). That two-phase teardown is the documented contract
-- from migration 076 — not a quirk of this file.
-- ---------------------------------------------------------------------------
DELETE FROM pipeline_step_deps WHERE step_fk IN (SELECT id FROM pipeline_steps WHERE pipeline_fk = 9001);
DELETE FROM pipeline_step_requirements WHERE step_fk IN (SELECT id FROM pipeline_steps WHERE pipeline_fk = 9001);
DELETE FROM pipeline_steps WHERE pipeline_fk = 9001;
DELETE FROM pipelines WHERE id = 9001;
--
-- There is no `features` teardown any more, and no requirement detach before it
-- (req #3355): migration 20260811033413 dropped the table and the
-- `requirements.feature_fk` column that used to need clearing first.
--
-- Scoped to the EXACT ids this file is about to insert, never a BETWEEN range.
-- Explicit ids at 9001+ leave AUTO_INCREMENT immediately above the fixture band, so
-- the next organically-created row lands exactly where a growing range would
-- expand — and a later plan with one more epic label would delete it.
DELETE FROM epics WHERE id IN (9001, 9002, 9003, 9004);

-- ---------------------------------------------------------------------------
-- The fixture's OWN project + category.
--
-- The plan's requirements carry PRODUCTION category ids, and
-- requirements.category_fk is NOT NULL -> categories ON DELETE RESTRICT — the
-- same cross-database hazard the machine_fk remap exists for. Reusing them works
-- on today's darwin_dev only because the ids happen to coincide; against a
-- darwin_dev rebuilt from recreate_darwin_dev.sql the load would fail 1452 AFTER
-- the teardown above had dropped the previous fixture. Owning these two rows
-- removes the assumption.
--
-- Created idempotently and deliberately NOT torn down: the upserted requirements
-- keep pointing at the category, and the FK is RESTRICT.
-- ---------------------------------------------------------------------------
INSERT INTO projects (id, project_name, creator_fk) VALUES
  (9001, 'Swarm Orchestration Fixture', '37df7531-000d-4470-8be4-1792d8261f69')
AS new ON DUPLICATE KEY UPDATE project_name = new.project_name;

INSERT INTO categories (id, category_name, project_fk, creator_fk) VALUES
  (9001, 'Swarm Orchestration Fixture', 9001, '37df7531-000d-4470-8be4-1792d8261f69')
AS new ON DUPLICATE KEY UPDATE category_name = new.category_name;

-- ---------------------------------------------------------------------------
-- Epics (4) — one per distinct epic label in the plan. Since req #3355 dropped
-- the Feature layer, nothing in this fixture points at them: a requirement now
-- reaches its epic only through the step that links it.
-- ---------------------------------------------------------------------------
INSERT INTO epics (id, title, description, category_fk, creator_fk, sort_order) VALUES
  (9001, 'Swarm Substrate Rebuild', 'Epic from the 2026-07-25 Substrate Rebuild plan (req #3083).', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 0),
  (9002, 'Application Backlog', 'Epic from the 2026-07-25 Substrate Rebuild plan (req #3083).', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 1),
  (9003, 'Swarm Orchestration Feature', 'Epic from the 2026-07-25 Substrate Rebuild plan (req #3083).', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 2),
  (9004, 'Primary and Swarm Agentic Integration', 'Epic from the 2026-07-25 Substrate Rebuild plan (req #3083).', 9001, '37df7531-000d-4470-8be4-1792d8261f69', 3);

-- ---------------------------------------------------------------------------
-- Requirements (67) — every requirement some step links, upserted with live
-- metadata. pipeline_step_requirements.requirement_fk is ON DELETE RESTRICT, so
-- every referenced requirement must exist before the junction rows load.
--
-- ON DUPLICATE KEY UPDATE, not plain INSERT: darwin_dev already holds some of
-- these ids, and the fixture must refresh their status (step state is derived
-- from it) without disturbing anything else about the row.
-- ---------------------------------------------------------------------------
INSERT INTO requirements (id, title, requirement_status, coordination_type, ai_model, effort, category_fk, creator_fk, machine_fk, tracking, started_at, completed_at) VALUES
  (3041, 'Make the DarwinAI-Config base clone handled commonly with all sub-repos: hygiene preconditions must be ff-only SYNC, never SAVE. No operation may commit/push the live base clone except the primary''s own /save-primary-claude.', 'wontfix', 'implemented', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-07-25T11:03:58'),
  (3045, 'Collect agent telemetry ', 'met', 'deployed', 'sonnet', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T08:55:39'),
  (3050, 'darwin-mcp rearchitecture: Lambda-Rest as single DB gateway (clean-sheet REST transport)', 'met', 'implemented', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-07-25T17:34:59'),
  (3051, 'Documents page becomes editable', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T10:41:50'),
  (3056, 'Views show autonomy', 'met', 'implemented', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'SJO-LT-C72929B'), 0, NULL, '2026-07-25T10:05:13'),
  (3057, 'Junction POST returns 500 after committing the row (breaks Features linking)', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T09:15:30'),
  (3058, 'memory/api-gateway.md route tables are stale — full reconciliation', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T08:24:48'),
  (3059, 'Map pymysql IntegrityError to HTTP 409 in Lambda-Rest', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T10:04:37'),
  (3060, 'E2E coverage for the editable agent instruction registry', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T11:46:23'),
  (3061, 'Two stale backend test files fail on schema drift', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T00:59:00'),
  (3063, 'Instruction Edit In Place', 'met', 'implemented', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-07-25T11:26:25'),
  (3064, 'Aggregator Card Polish', 'met', 'implemented', 'sonnet', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'SJO-LT-C72929B'), 0, NULL, '2026-07-25T09:54:20'),
  (3065, 'Agent Context Polish', 'met', 'implemented', 'sonnet', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'SJO-LT-C72929B'), 0, NULL, '2026-07-26T11:03:04'),
  (3067, 'Instructions Table View — hardened generic edit-in-place table pattern', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T23:30:27'),
  (3068, 'Instructions need proper English titles, not kebab-case slugs', 'met', 'planned', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-07-25T11:26:26'),
  (3069, 'Statusline DevServ indicator never shows on dash-based /bin/sh (WSL/Linux) — works on macOS only', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-25T22:45:09'),
  (3071, 'Replace remaining window.confirm calls under /agents with the house dialog pattern', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T09:13:37'),
  (3072, 'Swarm substrate Phase 0+1 — eliminate shared-clone git corruption class (de-symlink, Primary-only sync, remove worker-to-Primary writes, full git audit)', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-25T20:49:24'),
  (3074, 'Agent Harness for Primary AI and Swarm', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-08-09T00:27:00'),
  (3075, 'agent_instructions.sort_order has no per-agent uniqueness guard — decide the invariant', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T09:49:34'),
  (3076, 'Test InstructionDeleteDialog data-loss vs boot-impact wording', 'met', 'deployed', 'opus', 'low', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T08:53:14'),
  (3077, 'Swarm substrate Phases 2-4 — per-session clone provisioning from local mirrors; retire git-worktree machinery (full worker independence)', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T02:53:18'),
  (3078, 'darwin-mcp: bounded list reads — Lambda 6 MB response ceiling 502s large resources', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-25T19:03:14'),
  (3079, 'WSL: migrate mcp_credentials.sh to the #3050 Cognito variable set (new darwin-mcp daemon fails with ''DB_HOST'' error until done)', 'met', 'discuss', 'sonnet', 'medium', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'SJO-LT-C72929B'), 0, NULL, '2026-07-26T02:14:10'),
  (3080, 'Swarm Orchestration Feature: discuss session to spec and file the requirements for a durable pipeline data type (plans stored in Darwin, rendered in SwarmView, executed by Primary AI)', 'met', 'discuss', 'fable', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T01:25:19'),
  (3082, 'Primary AI substrate parity - relocate Primary to ~/darwin/primary via the unified clone pattern (pipeline Stage 5)', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T07:10:46'),
  (3083, 'Substrate Rebuild Pipeline - plan tracking (single source of truth for the plan page)', 'met', 'implemented', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 1, NULL, '2026-07-27T10:53:33'),
  (3084, 'WSL verification 1 of 3: full MCP validation', 'met', 'implemented', 'sonnet', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'SJO-LT-C72929B'), 0, NULL, '2026-07-26T03:19:32'),
  (3085, 'WSL verification 2 of 3: full swarm session independence', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'SJO-LT-C72929B'), 0, NULL, '2026-07-26T09:42:38'),
  (3086, 'WSL verification 3 of 3: full primary session independence', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'SJO-LT-C72929B'), 0, NULL, '2026-07-31T09:19:49'),
  (3087, 'Primary gate execution + B5a cutover for clone substrate (#3077 Stage 3/4)', 'met', 'implemented', 'fable', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T06:01:35'),
  (3088, 'Substrate remediation: R18 freshness contract, R19 no-hardlinks, B3 skill cutover, R6 attribution coverage + gap tests', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T05:25:08'),
  (3089, 'provision-repo.sh venv step uses system python3 (3.9) — fastmcp needs 3.10+; canary-1 venv=failed', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T11:28:16'),
  (3090, 'Clone substrate canary-2: multi-repo session lifecycle validation (throwaway)', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T08:14:15'),
  (3091, 'Clone sessions hit the Claude Code folder-trust dialog — pre-trust session dirs at launch (blocks all autonomous workers)', 'met', 'implemented', 'fable', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T08:00:25'),
  (3092, 'Persist per-repo provisioning telemetry (mirror_action, venv) into the swarm session record', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T11:48:11'),
  (3093, '/swarm-complete Step 5.6 worker guard never fires — mcp-restart-if-stale.sh reads $PWD, but Step 0(d) cd s to mainRepoPath', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T11:29:45'),
  (3094, 'POST /profiles read-back returns other users rows (WHERE id=0 on a non-auto-increment id)', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-26T11:33:28'),
  (3095, 'Ground-truth breakdown of the Claude Code base token figure', 'met', 'planned', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'SJO-LT-C72929B'), 0, NULL, '2026-07-27T04:12:53'),
  (3096, 'Per-document actual-token capture for architecture/autoload docs', 'met', 'deployed', 'sonnet', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-07-26T12:43:30'),
  (3097, 'Post-relocation Primary verification battery (Mac mini) — executed by the NEW primary session', 'met', 'implemented', 'fable', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T18:56:50'),
  (3098, 'Capture machine, model, and effort for agent telemetry runs', 'met', 'deployed', 'sonnet', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-07-26T22:06:34'),
  (3105, 'Swarm-Complete can RDS Snapshot', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T00:33:55'),
  (3108, 'Cooperative inter-Claude message system: proactive status communication between Primary(s) and workers — design discussion', 'deferred', 'discuss', 'fable', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, NULL),
  (3110, 'Swarm Orchestration: groom the full design intent into Swarm Architect documentation', 'met', 'deployed', 'fable', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T01:52:32'),
  (3111, 'Swarm Orchestration: schema foundation - epic hierarchy + pipelines data type (migration, routes, darwin_dev fixtures)', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T02:48:28'),
  (3112, 'Swarm Orchestration: ordering & derivation engine - pure JS module with self-checking invariants (vitest)', 'met', 'deployed', 'fable', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T02:14:14'),
  (3113, 'Swarm Orchestration: MCP pipelines API - bounded resources + echo-verified mutation tools', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T04:43:18'),
  (3114, 'Swarm Orchestration: SwarmView pipelines UI - hooks, routes, list page + plan-rows table view', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T03:47:50'),
  (3115, 'Swarm Orchestration: Plan visualizer (no time anchor) - epic bands, swim lanes, batch boxes, drag-pan + three-level zoom', 'met', 'deployed', 'fable', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T05:53:33'),
  (3116, 'Swarm Orchestration: Primary execution doctrine + fail-loud pipeline watchdog', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T06:08:09'),
  (3117, 'Swarm Orchestration: cost rollup - server-side precompute at session completion + Time/Tokens display', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T06:17:49'),
  (3118, 'Swarm Orchestration: E2E + mutation-case acceptance battery', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T07:38:52'),
  (3119, 'Swarm Orchestration: final polish & showcase - full live 3083 plan in darwin_dev, dev-server walkthrough, executive summary', 'met', 'implemented', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T10:53:28'),
  (3121, 'DarwinSQL migration-number allocation collides across concurrent sessions (046/050/074x3) - decide scheme + normalize + enforce', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T05:16:29'),
  (3122, 'Pipeline junction scoping: creator_fk authorization call for pipeline_step_deps surrogate-id addressability (pre/post #3113 MCP exposure)', 'met', 'deployed', 'opus', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T06:04:54'),
  (3124, 'darwin_dev schema tests vs concurrent session DDL - shared-mutable-state isolation policy', 'deferred', 'discuss', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, NULL),
  (3125, 'Cross-tenant FK grief-lock: ownership-check FK targets on all creator_fk-bearing tables (test_runs.test_plan_fk + 10 siblings)', 'met', 'implemented', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-07-27T09:12:47'),
  (3126, 'STRICT_TRANS_TABLES decision: enable strict sql_mode on RDS (parameter-group change + staged regression)', 'met', 'discuss', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-07-27T08:54:00'),
  (3127, 'Primary cutover execution P3-P6: relocate Primary to ~/darwin/primary per runbook (follow-on to 3082)', 'met', 'discuss', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', (SELECT id FROM machines WHERE hostname = 'Macmini'), 0, NULL, '2026-07-27T18:56:51'),
  (3128, 'Instruction: executive summary', 'met', 'discuss', 'fable', 'xhigh', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-07-27T08:21:04'),
  (3129, 'Instructions refactor', 'met', 'discuss', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-07-27T10:00:27'),
  (3130, 'instruction: Polish pattern', 'met', 'discuss', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-07-27T08:34:18'),
  (3131, 'instruction: Reflection Pattern', 'met', 'discuss', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-07-27T08:30:05'),
  (3132, 'swarm-complete closeout gate: refuse session completion that leaves its requirement non-terminal (from 3082 breach)', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-07-27T08:00:48'),
  (3136, 'AWS Architect guiding principles document', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-08-02T12:14:40'),
  (3137, 'Agents Architect guiding principles document', 'met', 'deployed', 'opus', 'high', 9001, '37df7531-000d-4470-8be4-1792d8261f69', NULL, 0, NULL, '2026-08-02T12:04:32')
AS new ON DUPLICATE KEY UPDATE
  title = new.title,
  requirement_status = new.requirement_status,
  coordination_type = new.coordination_type,
  ai_model = new.ai_model,
  effort = new.effort,
  machine_fk = new.machine_fk,
  tracking = new.tracking,
  started_at = new.started_at,
  completed_at = new.completed_at;

-- ---------------------------------------------------------------------------
-- The pipeline. `active` is a STORED, human/Primary-controlled declaration of
-- intent about the plan as a whole — the only hand-set lifecycle in the feature.
-- ---------------------------------------------------------------------------
INSERT INTO pipelines (id, title, description, pipeline_status, machine_fk, creator_fk, started_at) VALUES
  (9001, 'Substrate Rebuild Pipeline', 'Recover from the .git/index corruption incident, eliminate the shared-clone corruption class, rebuild provisioning on per-session clones, then run the max-parallel feature DAG. Source of truth: requirement #3083.', 'active', (SELECT id FROM machines WHERE hostname = 'Macmini'), '37df7531-000d-4470-8be4-1792d8261f69', '2026-07-24 00:00:00');

-- ---------------------------------------------------------------------------
-- Steps (42) — one per plan row, id = plan step id.
--
-- NO state column is written because none exists: a step's state is derived from
-- its linked requirements (design rule 1). The plan's own `state` field
-- (done/active/pending) is therefore NOT stored — it is reproducible from the
-- requirement statuses upserted above, and storing it is exactly the hand-edited
-- field that let plan row 13 read "Scheduled" while five sessions ran.
--
-- title is the plan row's OWN `title` field — a short name ("Session Drain",
-- "Bounded MCP Reads"), 11-36 chars across this plan. `notes` holds the full
-- `summary` prose: the evidence, the disposition, the corrections.
--
-- Until req #3119 this loaded `short_title(summary)` into title and left the
-- plan's real `title` unread, so every step name was a truncated paragraph and
-- the visualizer's Step: Title mode showed 40 chars of description. A title is
-- a NAME, not the first line of the description — and the plan has carried the
-- names all along.
-- ---------------------------------------------------------------------------
INSERT INTO pipeline_steps (id, pipeline_fk, title, run, notes, completed_at, creator_fk) VALUES
  (9001, 9001, 'Session Drain', 'auto', 'Drain: close every open swarm session so substrate surgery starts with zero in-flight work', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9002, 9001, 'Bounded MCP Reads', 'auto', 'Bound every MCP list read under Lambda''s 6 MB response ceiling; heavy columns move to by-id reads', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9003, 9001, 'Dual-Path Purge', 'auto', 'Eliminate dual-path git access (symlinks deleted, all repos moved off Desktop into real dirs), audit every git call, pr-finalize made read-only, ff-only Primary sync, hard clean-Primary gate', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9004, 9001, 'Wontfix Fold-In', 'auto', 'Dispositioned wontfix; live scope folded into 3072 (W7 clean gate) and 3077 (C1 grep gate, C2 origin fingerprint)', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9005, 9001, 'Substrate Validation', 'auto', 'Validation: first full worker lifecycle run clean on the repaired substrate (also fixed the statusline dev-server indicator)', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9006, 9001, 'Test Repair', 'auto', 'Repair every pre-existing test failure - backend fixture drift, MCP count asserts, two harness scripts - so the full suite reads truly green', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9007, 9001, 'Green Baseline', 'auto', 'Record the all-passing regression baseline across every suite; the fixed reference point for the clone-substrate regression gate - RECORDED 2026-07-26: harness 3736/3736, Lambda-Rest 134, Cognito 18, mcp unit 252 / integration 688 / production 62 - all passing', '2026-07-26 01:30:00', '37df7531-000d-4470-8be4-1792d8261f69'),
  (9008, 9001, 'WSL MCP Setup', 'manual', 'MCP setup on machine 3 - strictly serial: (1) /primary-ai-sync brings the WSL workspace current, (2) req 3079 migrates credentials and stands up the darwin-mcp daemon. No step/time deps: eligible whenever the user is at the WSL box', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9009, 9001, 'WSL MCP Validation', 'manual', 'Verification 1 of 3 - full MCP validation: health, wrapper read+mutation round-trips, bounded list reads, all three darwin-mcp test tiers, auto-restart. No pipeline gate - runnable immediately after W1', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9023, 9001, 'Agent Context Polish', 'manual', 'Agent Context polish (session 2439, machine 3). CORRECTED 2026-07-26: #3079 completed at 02:14Z, session created 02:17Z - it has run on the NEW daemon + credentials from birth. No stale-stack risk; normal lifecycle applies', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9033, 9001, 'Agentic Telemetry Batch', 'auto', 'AGENTIC TELEMETRY BATCH - one swarm-start, two sessions: per-document actual-token capture for architecture documents (3096), machine/model/effort columns on agent telemetry runs (3098)', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9034, 9001, 'Token Ground-Truth', 'manual', 'Ground-truth breakdown of the Claude Code base token figure (spawned by #3065). Discuss coordination on the Windows/WSL machine — user starts and drives it there.', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9021, 9001, 'Mirror Layer', 'auto', 'MILESTONE 1 (R20): mirror layer + protections land first - mirror-update.sh with the R18 single-flight freshness contract (mandatory synchronous fetch at every provision, per-repo lock, loud failure) and provision-repo.sh with R19 --no-hardlinks fully-private clones (greenfield-verified). Reviewable unit before any cutover work', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9010, 9001, 'Clone Substrate Core', 'auto', 'Clone substrate core: B3 discovery + provisioning cutover (flag-gated), dual-mode cleanup, worker git_op guard, docs - wrapped in feature review, gap analysis, and full regression vs the step-7 baseline', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9026, 9001, 'Gate Remediation', 'auto', 'Substrate remediation from gate findings: R19 --no-hardlinks (tests assert the opposite today), R18 FRESH_WINDOW dedup + stale_ok degrade, B3 skill cutover (/swarm-start + /swarm-resume still hardcode wt- paths — breaks at flip time), R6 attribution coverage fix, MED/LOW gap tests. Blocks the flip and canaries.', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9028, 9001, 'Trust Dialog Fix', 'auto', 'CANARY CATCH (major): clone sessions are new project roots — Claude Code folder-trust dialog blocked both canaries; worktrees had inherited trust via their .git pointer. Fixed same-day: trust-session.sh pre-registers the trust entry in ~/.claude.json, wired into worker-launch-batch.sh before backend dispatch. Landed fa7ed2b.', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9025, 9001, 'Gate Reviews + Flip', 'auto', 'Primary gate execution: G-feature + G-gap reviews (done — 5 deviations, 12 gaps found), independent G-regression after remediation, then B5a flag flip (LAYOUT_DEFAULT_PROVISIONING -> clone) deployed via /primary-ai-swarm-complete. Mirrors+sessions layout created and 7 mirrors seeded 2026-07-26.', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9011, 9001, 'Clone Canary 1', 'auto', 'Canary: a docs-only requirement runs the first clone-provisioned session through its entire lifecycle', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9022, 9001, 'Clone Canary 2', 'auto', 'Clone canary 2 (Mac mini, #3077 R13): throwaway requirement exercising what canary 1 cannot - >=2 repos, mid-session /hygiene checkout of a third, npm install in the session clone, dev-server registration, pause -> resume -> undo round-trip, deploy path, and the mid-flight rm -rf isolation test. Throwaway req filed at execution time', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9012, 9001, 'Backlog Wave', 'auto', 'Seven parallel sessions on the proven substrate: house dialog pattern under /agents, IntegrityError-to-409 mapping, junction-POST 500 fix, editable Documents page, agent telemetry collection, delete-dialog wording test, sort-order invariant decision', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9013, 9001, 'Post-Wave Batch', 'auto', 'POST-WAVE BATCH - one swarm-start, five sessions: provision-repo.sh venv python3.10+ fix (3089), per-repo provisioning telemetry persisted to the session record (3092), mcp-restart-if-stale.sh cross-session write to the PRIMARY clone (3093), E2E coverage for the editable agent instruction registry (3060), SECURITY POST /profiles read-back cross-tenant leak (3094)', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9014, 9001, 'Instructions Table View', 'auto', 'Instructions Table View - hardened generic edit-in-place table pattern', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9016, 9001, 'WSL Clone Testing', 'manual', 'Verification 2 of 3 - WSL CLONE TESTING (mirror of the mini canaries on machine 3): mirrors + session-clone layout via the same scripts, real /swarm-start full lifecycle, write isolation, machine-pin routing. The clone mechanism is proven per-machine, never assumed portable', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9017, 9001, 'Primary Relocation', 'manual', 'PLAN-COMPLETION GATE. Relocate Primary to ~/darwin/primary via the same clone pattern as workers; migrate memory, config, and MCP daemon; decommission the old path (no dual-path overlap); validation battery ends with a canary swarm launch from the new home', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9031, 9001, 'Relocation Verification', 'manual', 'Human-verified #3082 battery, executed BY the new primary session at ~/darwin/primary after cutover: layout resolution, MCP, statusline walk-ups, dev server, a canary /swarm-start from the new home, hooks/darcfg, old-path decommission audit. Failures file defects, never inline patches.', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9018, 9001, 'WSL Primary Parity', 'manual', 'Verification 3 of 3 - full primary session independence: execute the step-12 runbook on machine 3, old-path decommission, validation battery from the new home. Completes WSL parity', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9019, 9001, 'Orchestration Spec', 'auto', 'Cherry: discuss session specs the pipelines-as-data feature and files its follow-on requirements - this plan is its seed dataset, held by tracking req 3083 (single source of truth this page renders from) + BATCHED same launch: swarm-complete RDS-snapshots without asking permission (3105, cross-epic per rule 10)', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9020, 9001, 'Agent Infra Leverage', 'auto', 'Darwin Primary AI and swarm workers leverage the Agent infrastructure (final step of the plan)', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9038, 9001, 'Foundation Wave', 'auto', 'FOUNDATION BATCH - one swarm-start, three sessions: design-intent grooming into Swarm Architect docs (3110), schema foundation - epics/features/requirements hierarchy + pipelines/pipeline_steps/step-requirements/step-deps tables + API routes + darwin_dev fixtures from this plan (3111), pure-JS ordering/derivation engine with self-checking invariants (3112)', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9039, 9001, 'API + Table Wave', 'auto', 'API & TABLE BATCH: MCP pipelines resources + echo-verified mutation tools with single-read render (3113); SwarmView pipelines hooks/routes/list page + plan-rows table view per pipeline-plan-tracking rules (3114)', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9040, 9001, 'Visualizer + Doctrine Wave', 'auto', 'VISUALIZER & DOCTRINE BATCH: Plan (no time anchor) visualizer with drag-pan + three-level zoom, clickable steps/reqs/epics (3115); Primary execution doctrine + 8-case mutation playbook + fail-loud watchdog (3116); server-side cost rollup + Time/Tokens enable (3117) + BATCHED: pipeline junction creator_fk/authorization call, audited against 3113''s shipped MCP surface (3122, from 3111 security flag)', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9041, 9001, 'Acceptance Battery', 'auto', 'Acceptance battery: Playwright E2E over the seeded darwin_dev plan + replay of all 8 recorded mutation classes via MCP tools, asserting derived state and invariant-clean rendered order after each', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9042, 9001, 'Polish + Showcase', 'auto', 'FINAL POLISH & SHOWCASE (implemented - the epic''s only user-review stop): re-seed darwin_dev with the full live 3083 plan, cosmetic polish pass, dev server deep-linked to /swarm/pipelines, concise executive summary; user checks all features', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9043, 9001, 'Messaging Design', 'manual', 'Design discussion (discuss, user-driven): cooperative inter-Claude message system - grounded by the shipped orchestration core + Primary doctrine; informs future proactive Primary/worker communication | req 3108 deferred 2026-07-27', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9044, 9001, 'Migration Numbering', 'auto', 'Migration-number allocation collides across concurrent sessions (046/050/074x3, found by 3111): decide scheme, normalize existing collisions safely, enforce uniqueness with a test', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9045, 9001, 'Primary Cutover', 'manual', 'CUTOVER EXECUTION (follow-on to 3082, filed after the partial-closeout ruling): fresh user session (cd ~ && claude) runs memory/primary-cutover-runbook.md P3-P6 - relocate Primary to ~/darwin/primary, retire the legacy root. NOT a swarm session; old-home Primary hands off and retires. HARD PRECONDITION: no swarm session in flight.', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9046, 9001, 'FK Grief-Lock Fix', 'auto', 'Cross-tenant FK grief-lock (from 3122''s report): ownership-check FK targets on all creator_fk-bearing tables (test_runs.test_plan_fk + 10 siblings) using the 3122 MySQL-grammar pattern; waits-only-because-single-tenant class', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9047, 9001, 'Data-Layer Decisions', 'manual', 'TWO DISCUSS SESSIONS, one swarm-start: darwin_dev schema tests vs concurrent session DDL isolation policy (3124, from 3121''s report) + STRICT_TRANS_TABLES enablement decision (3126, from 3122''s report). User-driven | 3126 closed met 2026-07-27; 3124 deferred', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9048, 9001, 'Closeout Gate', 'auto', 'ENFORCEMENT FIX for the 3082 partial-closeout breach: /swarm-complete refuses any closeout leaving its requirement non-terminal unless a filed follow-on req + met-scoped closeout accompany it; deployed-worker doctrine + multi-executor authoring split rule; harness tests', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9049, 9001, 'Lesson Learned', 'auto', 'AGENTIC REFACTOR step 1 - three instruction requirements in one swarm-start (discuss, user-driven content): executive summary instruction (3128), Polish pattern instruction (3130), Reflection Pattern instruction (3131) | Epic gate: could not start until MCP server done (step 2/1) and substrate re-architecture hardened (step 13) - both complete', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9050, 9001, 'Guiding Principles and Data Refactor', 'auto', 'AGENTIC REFACTOR step 2 (discuss, user-driven): Instructions refactor - guiding principles + data refactor of the instruction registry | Epic gate: could not start until MCP server done (step 2/1) and substrate re-architecture hardened (step 13) - both complete', NULL, '37df7531-000d-4470-8be4-1792d8261f69'),
  (9051, 9001, 'Agentic Cleanup', 'manual', 'AGENTIC REFACTOR step 3 - agentic cleanup: author the two missing guiding-principles charters, AWS Architect (3136) and Agents Architect (3137). Both filed by 3129; the principles relationship role only exists once the 3129 refactor lands | Manual start; gated on BOTH Lesson Learned (49) and Guiding Principles and Data Refactor (50)', NULL, '37df7531-000d-4470-8be4-1792d8261f69');

-- ---------------------------------------------------------------------------
-- Step -> requirement links (68). A step is a LAUNCH UNIT: steps 1, 33, 12, 13, 19, 38, 39, 40, 47, 49, 51 carry
-- more than one requirement because those requirements went out in ONE
-- swarm-start (design rule 2).
-- ---------------------------------------------------------------------------
INSERT INTO pipeline_step_requirements (step_fk, requirement_fk) VALUES
  (9001, 3050),
  (9001, 3056),
  (9001, 3063),
  (9001, 3064),
  (9001, 3068),
  (9002, 3078),
  (9003, 3072),
  (9004, 3041),
  (9005, 3069),
  (9006, 3061),
  (9008, 3079),
  (9009, 3084),
  (9023, 3065),
  (9033, 3096),
  (9033, 3098),
  (9034, 3095),
  (9021, 3077),
  (9010, 3077),
  (9026, 3088),
  (9028, 3091),
  (9025, 3087),
  (9011, 3058),
  (9022, 3090),
  (9012, 3071),
  (9012, 3059),
  (9012, 3057),
  (9012, 3051),
  (9012, 3045),
  (9012, 3076),
  (9012, 3075),
  (9013, 3089),
  (9013, 3092),
  (9013, 3093),
  (9013, 3060),
  (9013, 3094),
  (9014, 3067),
  (9016, 3085),
  (9017, 3082),
  (9031, 3097),
  (9018, 3086),
  (9019, 3080),
  (9019, 3083),
  (9019, 3105),
  (9020, 3074),
  (9038, 3110),
  (9038, 3111),
  (9038, 3112),
  (9039, 3113),
  (9039, 3114),
  (9040, 3115),
  (9040, 3116),
  (9040, 3117),
  (9040, 3122),
  (9041, 3118),
  (9042, 3119),
  (9043, 3108),
  (9044, 3121),
  (9045, 3127),
  (9046, 3125),
  (9047, 3124),
  (9047, 3126),
  (9048, 3132),
  (9049, 3128),
  (9049, 3130),
  (9049, 3131),
  (9050, 3129),
  (9051, 3136),
  (9051, 3137);

-- ---------------------------------------------------------------------------
-- Dependency edges from the plan (45). Structured rows, never prose
-- (design rule 4). Exactly one of dep_step_fk / time_at per row. dep_step_fk is
-- ON DELETE RESTRICT, which is what makes a referenced step undeletable.
-- ---------------------------------------------------------------------------
INSERT INTO pipeline_step_deps (step_fk, dep_step_fk, time_at) VALUES
  (9003, 9001, NULL),
  (9004, 9003, NULL),
  (9005, 9003, NULL),
  (9006, 9005, NULL),
  (9007, 9006, NULL),
  (9009, 9008, NULL),
  (9033, 9023, NULL),
  (9034, 9023, NULL),
  (9021, 9007, NULL),
  (9010, 9021, NULL),
  (9026, 9010, NULL),
  (9028, 9025, NULL),
  (9025, 9010, NULL),
  (9025, 9026, NULL),
  (9011, 9025, NULL),
  (9022, 9011, NULL),
  (9012, 9011, NULL),
  (9012, 9022, NULL),
  (9012, 9028, NULL),
  (9013, 9012, NULL),
  (9014, 9012, NULL),
  (9014, 9013, NULL),
  (9016, 9009, NULL),
  (9016, 9011, NULL),
  (9017, 9012, NULL),
  (9017, 9013, NULL),
  (9017, 9014, NULL),
  (9031, 9045, NULL),
  (9018, 9016, NULL),
  (9018, 9045, NULL),
  (9019, 9014, NULL),
  (9020, 9045, NULL),
  (9020, 9031, NULL),
  (9038, 9019, NULL),
  (9039, 9038, NULL),
  (9040, 9039, NULL),
  (9041, 9040, NULL),
  (9042, 9041, NULL),
  (9043, 9040, NULL),
  (9049, 9002, NULL),
  (9049, 9013, NULL),
  (9050, 9002, NULL),
  (9050, 9013, NULL),
  (9051, 9049, NULL),
  (9051, 9050, NULL);

-- ---------------------------------------------------------------------------
-- THE DUAL-CONDITION GATE (s0.4) — reconstructed, and separated from the block
-- above so its provenance cannot be mistaken.
--
-- req #3080, plan stage 0: "s0.4 gate: #3050 session completed AND 2h time gate
-- 06:31:38 PDT (done — note: DUAL-condition gate, two independent wait
-- mechanisms)". The live PLAN-JSON carries no T: tokens: the 2026-07-25
-- normalization that replaced the 0/2a/Wx/Px ids dropped the wall-clock condition
-- with the stage numbering. This row restores it on the step that actually waited
-- on it — step 3 (#3072, the first substrate surgery), which already gates on
-- step 1 (the drain, where #3050 landed). Step 3 therefore ends up with two dep
-- rows of DIFFERENT kinds, which is what a dual-condition gate is and what the
-- acceptance criterion asks this schema to prove it can hold.
-- ---------------------------------------------------------------------------
INSERT INTO pipeline_step_deps (step_fk, dep_step_fk, time_at) VALUES
  (9003, NULL, '2026-07-24 06:31:38');

-- Verification the loader can eyeball:
--   SELECT COUNT(*) FROM pipeline_steps             WHERE pipeline_fk = 9001;  -- 42
--   SELECT COUNT(*) FROM pipeline_step_requirements WHERE step_fk IN (SELECT id FROM pipeline_steps WHERE pipeline_fk = 9001);  -- 68
--   SELECT COUNT(*) FROM pipeline_step_deps         WHERE step_fk IN (SELECT id FROM pipeline_steps WHERE pipeline_fk = 9001);  -- 46
